### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Dimatert9** [Shevchik/ProtocolSupportBungee#1]
http://pastebin.com/yVg4W7H8

**Comment by Dimatert9** [comment]
I have ProtocolSuppoer on spigot server

**Comment by Dimatert9** [comment]
Plugins if you need.
http://i.gyazo.com/1dc91ad74398b17398c05479755ea016.png
http://i.gyazo.com/19fcfdaca77ea8d17203a90cef8b5228.png

**Comment by Dimatert9** [comment]
Можешь сделать штуку, чтобы для версий 1.5-1.6 и 1.7-1.8 было разное motd в главном меню?
Просто Хочется чтобы на 1.7-1.8 было в 2 строчки, а на 1.5-1.6 в одну строчку мотд.

**Comment by Shevchik** [comment]
Update to lastest build, enable logging using /ps debug, try again, then send me the log.

**Comment by Dimatert9** [comment]
http://pastebin.com/erMNBgzD

**Comment by Dimatert9** [comment]
Вот. Появилась опять. http://pastebin.com/Skqw80WT

**Comment by Shevchik** [comment]
Problems with 1.7 is bungee own problem.

Try without plugins, something is really wrong. Are you sure that you are running latet ProtocolSupport build?

**Comment by Dimatert9** [comment]
I try without plugins, and again i have this error.
I have no plugins in bungeecord and spigot server. Only protocolsupport. I have latest BungeeCord, and Spigot.
http://pastebin.com/nCVgWYmv

**Comment by Dimatert9** [comment]
Блиин. Почему ты не написал что плагин работает токо с 1065 билдом. Напиши это на гитхабе, я на спиготе не смотрел этот плагин.
