### ISSUE TITLE
1.6 and 1.5 have errors connecting to a bungeecord server with ProtocolSupport

### ISSUE THREAD

**Issue by Tom-III** [Shevchik/ProtocolSupportBungee#3]
I get this message when I try to connect to a 1.8 Spigot server using latest ProtocolSupport and latest bungeecord using latest PSBungee.  I think it has something to do with usernames since usernames *should* be 16 characters but the client is receiving something bigger.

![Disconnect screen](http://i.imgur.com/gYJV0a2.png)

17.08 11:56:45 [Server] INFO [To Server] Sent packet(id: 250, defined data: PluginMessage(tag=REGISTER, data=[66, 84, 76, 80, 0, 70, 79, 82, 71, 69, 0, 70, 77, 76, 0, 70, 77, 76, 124, 72, 83, 0, 66, 117, 110, 103, 101, 101, 67, 111, 114, 100], allowExtendedPacket=false))
17.08 11:56:45 [Server] INFO [From Server] Received packet(id: 1, length: 26, defined data: Login(entityId=54003, gameMode=0, dimension=0, difficulty=1, maxPlayers=60, levelType=default, reducedDebugInfo=true))
17.08 11:56:45 [Server] INFO [To Server] Sent packet(id: 2, defined data: Handshake(protocolVersion=78, host=mc.skyprison.net
[{"name":"textures","value":"eyJ0aW1lc3RhbXAiOjE0Mzk4MDUyOTcxMjUsInByb2ZpbGVJZCI6IjVlYWE4MWMyYzYwYTQ0MzViZjgwNzAwZGIyZmNkYTA1IiwicHJvZmlsZU5hbWUiOiJzcXVpcnJlbG1haWwiLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYWM1NmZiZDQxOTg4ZTE4NjQ3OGQ5OGVjNjk5MWQwNzI1ZWFiZGE5ZGQzZWM0YTQ3OGM0OGVkZmVmYTVkMjQifX19","signature":"SfGAklZ9IOfUJYak72Jz71LJsAxgoCg5y5poUH/eX2rf5fhJqFNUGYgnPVCc6psGTSS8woksr4MTW2UyzD53zIogxySE7rrjZD/mR52Y0H43Amy3aRp93GyYjwrsL5qQMeHcUzmhQdfQcVvqHr4wLHlAlfBgi/azd8/nPOCOzSViizZYaXCzrmIwyU/y+3aGiPGnTT4icKVYyUPCbs6e89QeMuJX4DbroFpfd19Eeg6+PWsKhFnc/y4KQUnSVpyU7RvMSEPziioYIzJ6rKXSD8K5BUA3idV7QJJPX8LAo/kbtoJtAAWgX1GJAtVQZVi5ihdj3x1zBORtzlK1jTkl5294qxAX8r74ST3L4vJWbvXcZDvudbdgKuqDpjaFnD+o0oj/WkIjVeij2/1SIJrSjLKZzzbC+Cssd/CsyOSOi1etoNjN9ZyqcDpCqb9RLditnvHg1usearDtksiV9MzdmGblNIGLbgG+7zp0h+8m/zwgBHch7SjkR6Lk444QrSJYZM8W3Mhs0ZLY7O2jpgnI0XzbqMG5mrliJdAmkJU/k5ngKlA03YT33KoNyjbNFaWEVXI6K1nx4b47gNv7dAOTp1RIUDwqYOpBJBbc6mUOBtAD+jGV/HIITJGF6NFzGTtkDwXVaxQJURHm9IuRNss1TyWpaPtFEyfc7x5wnXbkIhk\u003d"}], port=25565, requestedProtocol=2))

17.08 11:56:45 [Server] INFO [To Client] Sent packet(id: 250, defined data: PluginMessage(tag=REGISTER, data=[66, 84, 76, 80, 0, 70, 79, 82, 71, 69, 0, 70, 77, 76, 0, 70, 77, 76, 124, 72, 83, 0, 66, 117, 110, 103, 101, 101, 67, 111, 114, 100], allowExtendedPacket=false))

**Comment by Shevchik** [comment]
Looks more like cusotm payload problem for me.

**Comment by Tom-III** [comment]
Thats because the IP in the log isnt the IP of the server that im connecting to.  Im connecting to a latest bungeecord that forces me to the server that has ProtocolSupport installed.  The rest of the servers in the network are spigot 1649 protocol hack servers

**Comment by Shevchik** [comment]
Well, can't help there, this problem reqires manual debugging. Check if you have some plugins that modify tablist.

**Comment by Tom-III** [comment]
BungeeTabsListPlus modifies the tablist

**Comment by Shevchik** [comment]
I added player list packet display name trimming, try again

**Comment by CodeCrafter47** [comment]
I've looked at why BungeeTabListPlus isn't working together with this plugin. I identified two issues.
First: For 1.5 and 1.6 players ProxiedPlayer.getPendingConnection().getVersion() returns 47, thus BungeeTabListPlus applies 1.8 tablist code. I used the following patch to make it return 5 (1.7.10), that made BungeeTabListPlus thinking the player uses minecraft 1.7, so it is aware of the 16 characters limit.
```
diff --git a/src/protocolsupport/protocol/transformer/v_1_5_v1_6_shared/packets/HandshakePacket.java b/src/protocolsupport/protocol/transformer/v_1_5_v1_6_shared/packets/HandshakePacket.java
index 44f3b34..b6e8430 100644
--- a/src/protocolsupport/protocol/transformer/v_1_5_v1_6_shared/packets/HandshakePacket.java
+++ b/src/protocolsupport/protocol/transformer/v_1_5_v1_6_shared/packets/HandshakePacket.java
@@ -15,7 +15,7 @@ public class HandshakePacket extends Handshake implements TransformedPacket {
        private int requestedstate = 2;
 
        public HandshakePacket() {
-               this.protocolversion = ProtocolVersion.MINECRAFT_1_8.getId();
+               this.protocolversion = ProtocolVersion.MINECRAFT_1_7_10.getId();
        }
 
        public HandshakePacket(int protocolversion, String username, String host, int port) {
```
I don't know whether there are any side effects of changing the protocol version.

Second: Team packets are not sent. BungeeTabListPlus can modify the tablist without using team packets but I've only implemented that possibility on bungee versions prior 1.8 support. So team packets are required or the tablist will be plank. I used the following patch to make team packets work:
```
diff --git a/src/protocolsupport/protocol/transformer/v_1_5_v1_6_shared/reader/BungeePacketTransformer.java b/src/protocolsupport/protocol/transformer/v_1_5_v1_6_shared/reader/BungeePacketTransformer.java
index d99f128..93bedbe 100644
--- a/src/protocolsupport/protocol/transformer/v_1_5_v1_6_shared/reader/BungeePacketTransformer.java
+++ b/src/protocolsupport/protocol/transformer/v_1_5_v1_6_shared/reader/BungeePacketTransformer.java
@@ -1,32 +1,14 @@
 package protocolsupport.protocol.transformer.v_1_5_v1_6_shared.reader;
 
+import net.md_5.bungee.protocol.packet.*;
 import protocolsupport.api.ProtocolSupportAPI;
 import protocolsupport.protocol.transformer.TransformedPacket;
-import protocolsupport.protocol.transformer.v_1_5_v1_6_shared.packets.ChatPacket;
-import protocolsupport.protocol.transformer.v_1_5_v1_6_shared.packets.EncryptionRequestPacket;
-import protocolsupport.protocol.transformer.v_1_5_v1_6_shared.packets.KeepAlivePacket;
-import protocolsupport.protocol.transformer.v_1_5_v1_6_shared.packets.KickPacket;
-import protocolsupport.protocol.transformer.v_1_5_v1_6_shared.packets.LoginPacket;
-import protocolsupport.protocol.transformer.v_1_5_v1_6_shared.packets.PlayerListItemPacket;
-import protocolsupport.protocol.transformer.v_1_5_v1_6_shared.packets.PluginMessagePacket;
-import protocolsupport.protocol.transformer.v_1_5_v1_6_shared.packets.RespawnPacket;
+import protocolsupport.protocol.transformer.v_1_5_v1_6_shared.packets.*;
 import protocolsupport.utils.PingSerializer;
 import protocolsupport.utils.Utils;
 import io.netty.buffer.ByteBuf;
 import io.netty.channel.Channel;
 import net.md_5.bungee.protocol.DefinedPacket;
-import net.md_5.bungee.protocol.packet.Chat;
-import net.md_5.bungee.protocol.packet.EncryptionRequest;
-import net.md_5.bungee.protocol.packet.KeepAlive;
-import net.md_5.bungee.protocol.packet.Kick;
-import net.md_5.bungee.protocol.packet.Login;
-import net.md_5.bungee.protocol.packet.LoginSuccess;
-import net.md_5.bungee.protocol.packet.PlayerListHeaderFooter;
-import net.md_5.bungee.protocol.packet.PlayerListItem;
-import net.md_5.bungee.protocol.packet.PluginMessage;
-import net.md_5.bungee.protocol.packet.Respawn;
-import net.md_5.bungee.protocol.packet.StatusResponse;
-import net.md_5.bungee.protocol.packet.Title;
 
 public class BungeePacketTransformer {
 
@@ -73,6 +55,17 @@ public class BungeePacketTransformer {
                        Login login = (Login) packet;
                        return new TransformedPacket[] { new LoginPacket(login.getEntityId(), login.getGameMode(), (byte) login.getDimension(), login.getDifficulty(), login.getMaxPlayers(), login.getLevelType())
                }
+               if (packet instanceof Team) {
+                       Team team = (Team) packet;
+                       TeamPacket transformedPacket = new TeamPacket(team.getName());
+                       transformedPacket.setMode(team.getMode());
+                       transformedPacket.setPrefix(team.getPrefix());
+                       transformedPacket.setSuffix(team.getSuffix());
+                       transformedPacket.setDisplayName(team.getDisplayName());
+                       transformedPacket.setPlayers(team.getPlayers());
+                       transformedPacket.setFriendlyFire(team.getFriendlyFire());
+                       return new TransformedPacket[] { transformedPacket };
+               }
                return null;
        }
```

Unrelated:
The spigot plugin doesn't work if late-bind is set to true.
1.6.* clients crash when they receive chat messages sent by bungee plugins.

**Comment by Shevchik** [comment]
Bungee will drop 1.7 support soon anyway, so switching back to 1.7.10 won't work in the future.
I have added a tablist name clamp so this won't be a problem in the future.
Yea, i didn't implement scoreboard packets transformer because there was no way to send them through api, will implement them later.

**Comment by CodeCrafter47** [comment]
That's fine. Then I will make BungeeTabListPlus use your api to get the correct client version.

**Comment by Tom-III** [comment]
It would be nice to have bungeetabslistplus working in 1.6/1.5, players haver requested it on a server I administrate.

**Comment by CodeCrafter47** [comment]
Since the necessary changes to this plugin have been made, I will update BungeeTabListPlus now.
