### ISSUE TITLE
In the NotDefinedPacketReader classes the BYTES have errors.

### ISSUE THREAD

**Issue by Tom-III** [Shevchik/ProtocolSupportBungee#4]
The java files have errors in them, is it due to a missing library?  My IDE is setup with Java 7
![Error message](http://i.imgur.com/0YD04Hz.png)
Can not resolve symbol BYTES

**Comment by Shevchik** [comment]
That's because it is a symbol from 1.8.

**Comment by Tom-III** [comment]
Did this plugin always need Java 8?

**Comment by Shevchik** [comment]
Yep.

**Comment by Tom-III** [comment]
From the start really?
Well maybe my the server machine had java8 and I didn't know, I'm an admin and I don't own the machine, another admin owns it
